[debops.logrotate] keep newlines in config
These changes remove the Jinja 'strip' operations from the logrotate templates. Logrotate does not like missing newlines and presented us with errors like these:

```
/etc/cron.daily/logrotate:
error: php7.0-fpm:prerotate, postrotate or preremove without endscript
error: found error in file php7.0-fpm, skipping
error: rsyslog:prerotate, postrotate or preremove without endscript
error: found error in file rsyslog, skipping
error: rsyslog-remote:prerotate, postrotate or preremove without endscript
error: found error in file rsyslog-remote, skipping
error: /etc/logrotate.conf:14 bad rotation count '1}'
error: found error in /var/log/wtmp , skipping
```

These errors were all caused by missing newlines. For example, 'endscript' and the curly bracket after the '1' must be on new lines.
I'm not sure why the 'strip' operation was in the templates in the first place. Maybe I'm overlooking something, but this seems to work for us.