Fix the error: 'dict object' has no attribute 'groovy'.
(cherry picked from commit dfca7485a769acea16543b55b5070c8eefe56547)
(cherry picked from commit a044d283ae6b47162aa995a4149099d2d1b9ef1a)