fix(playbooks): Fix regression in dist-upgrade.yml from 2021-03-19
Error: /bin/sh: 1: set: Illegal option -o pipefail
Ref: b877fc2d7b6f5bd345c1ed90ead703fc2087711c