fix potential logic error for interfaces managed by systemd
the way i understand this code is that `systemd_interface_instances` track all
the interfaces that are managed by systemd. so if `iface_name` is not in
`systemd_interface_instances` then restart networking and sync.

Where correctly it should be if `iface_name` is in `systemd_interface_instances`
then state is correct and continue with restarting networking and sync.

This resulting in errors like these when I attempt to use this script, with
added debug lines. Let me know if i'm off or this was a red herring since I'm
new to this code base.

```
$ sudo /usr/local/lib/ifupdown-reconfigure-interfaces
Detected interfaces to reconfigure: bond0,enp1s0f0,enp1s0f1
Detected interfaces to reconfigure: bond0,enp1s0f0,enp1s0f1
Found active systemd ifup@ instances: bond0,enp1s0f0,enp1s0f1
Found active systemd iface@ instances: bond0,enp1s0f0,enp1s0f1,
Found active systemd iface@ instances: bond0,enp1s0f0,enp1s0f1,
Bringing down 'enp1s0f1' interface
inspect enp1s0f1, and active systemd iface@ instances: bond0,enp1s0f0,enp1s0f1,,
Error: Script was working on 'enp1s0f1' network interface when it lost knowledge about the network interface state. The '/etc/network/interfaces.d/' might be desynchronized. Exiting to avoid loss of connectivity, investigate the issue.

```

thanks,

(cherry picked from commit 6541b794642f945a52aa4ad4739fbbbb710744c5)
(cherry picked from commit 84b9d35d4ee3e203b620ab00b2aa2087d2924df8)