[ci] Install python3-netaddr on the controller
ansible-lint seems to have gained the ability to analyse jinja2 templates.

This patch fixes errors like:
Error: An unhandled exception occurred while running the lookup plugin 'template'.
Error was a <class 'ansible.errors.AnsibleFilterError'>, original message:
The ipaddr filter requires python's netaddr be installed on the ansible controller.

(cherry picked from commit d54b350ec3ad1f6aaa6c48fbfc03e1e1273fc5a8)